version: '3'

services:
  app:
    build:
      context: .
    container_name: booklibra
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/booklibra?currentSchema=develop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    ports:
      - '8088:8088'

  db:
    image: postgres:15.1-alpine
    container_name: booklibra_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=booklibra
    volumes:
      - ./src/main/resources/db-init:/docker-entrypoint-initdb.d