server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/booklibra?currentSchema=develop
    username: postgres
    password:
    driver-class-name: org.postgresql.Driver
  flyway:
    baselineOnMigrate: true
    fail-on-missing-locations: true
    locations: classpath:db/migration
    schemas: develop
    enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

security:
  jwt:
    secret: c3VwZXJwdXBlcmR1cGVybWVnYWhhcmRvdmVydG9waGlnaHNlY3JldA==
    access: 3600000
    refresh: 2592000000

logging:
  level:
    ru.egorov.booklibrary : INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    name: 'app.log'
